"""Build the agent skills catalog from the ``skills/*/SKILL.md`` files.

The catalog is a markdown note written into the vault so that agents (and you)
can discover, at a glance, every automation skill this Atlas OS install ships.
Each skill's ``name`` and ``description`` are read from its SKILL.md YAML
frontmatter — the single source of truth — so the catalog never drifts.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from atlas_os._paths import skills_dir

# Suggested cadences, keyed by skill name. Mirrors docs/SCHEDULED-TASKS.md.
# A skill missing here simply shows "—"; nothing breaks.
_CADENCES: dict[str, str] = {
    "nightly-obsidian-index": "Nightly (~02:00)",
    "nightly-rag-incremental": "Nightly (after the index)",
    "daily-job-tracker-update": "Weekday mornings",
    "afternoon-job-tracker-update": "Weekday ~14:00",
    "atlas-daily-report-email": "Daily (~09:30)",
    "daily-trading-report": "Daily (~13:00)",
    "friday-it-newsletter": "Fridays AM",
    "weekly-system-health-check": "Weekly",
    "weekly-rag-full-reembed": "Weekly (Sun early AM)",
}


@dataclass(frozen=True)
class Skill:
    """One installable agent skill, read from its SKILL.md frontmatter."""

    slug: str  # folder name
    name: str
    description: str
    cadence: str


def _parse_frontmatter(text: str) -> dict[str, object]:
    """Return the YAML frontmatter block of a markdown file, or {}."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    try:
        loaded = yaml.safe_load(text[3:end])
    except yaml.YAMLError:
        return {}
    return loaded if isinstance(loaded, dict) else {}


def load_skills() -> list[Skill]:
    """Discover every skill under the skills/ directory, sorted by name."""
    root = skills_dir()
    skills: list[Skill] = []
    for skill_md in sorted(root.glob("*/SKILL.md")):
        slug = skill_md.parent.name
        meta = _parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        name = str(meta.get("name") or slug)
        description = str(meta.get("description") or "").strip()
        skills.append(
            Skill(
                slug=slug,
                name=name,
                description=description,
                cadence=_CADENCES.get(slug, "—"),
            )
        )
    return skills


def render_catalog(skills: list[Skill], generated_on: str | None = None) -> str:
    """Render the catalog note (markdown with frontmatter)."""
    stamp = f"\ngenerated: {generated_on}" if generated_on else ""
    rows = "\n".join(
        f"| **{s.name}** | {s.description} | {s.cadence} |" for s in skills
    )
    return f"""\
---
title: Skills Catalog
type: reference
tags: [atlas-os, skills, agents]{stamp}
---

# Skills Catalog

The automation **skills** available in this Atlas OS install. Each is a
Claude Cowork skill (a `SKILL.md` prompt) that an agent can run on a schedule or
on demand. Agents: read this note to discover what you can invoke; cadences are
suggestions (see the project's `docs/SCHEDULED-TASKS.md`).

> Auto-generated by `atlas skills --sync`. Re-run it after adding or changing a
> skill — do not hand-edit, your changes will be overwritten.

| Skill | What it does | Suggested cadence |
|---|---|---|
{rows}

_{len(skills)} skill(s). To install one, copy its `skills/<slug>/` folder into
your Claude scheduled-tasks directory and replace the `{{{{PLACEHOLDER}}}}`
tokens. See `docs/SCHEDULED-TASKS.md`._
"""


def default_catalog_path(vault: Path) -> Path:
    """Where the catalog note lives in the vault."""
    return vault / "Skills Catalog.md"
